name: flutter_slidable
description: A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
version: 0.5.7-nullsafety.1
homepage: https://github.com/letsar/flutter_slidable
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1

environment:
  sdk: ">=2.11.0-213.0.dev <2.12.0"
